/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClientSide;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import ClientSide.*;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;

/**
 *
 * @author sarah
 */
public class Availability extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Availability.class.getName());

    /**
     * Creates new form Availability101
     */
    public Availability() {
        initComponents();
    }
    //Declaration of the var:
<<<<<<< HEAD
    String src, dest, cls;
    Client  client ;
    public Availability(Client client, String source, String destination, String class_) {
    this.client = client;
    src =source;
    dest =destination;
    cls = class_;
    initComponents(); 
    setLocationRelativeTo(null);
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
=======

    Client client;
    boolean changeMode;

    public Availability(Client client, boolean changeMode) {
        this.client = client;
        this.changeMode= changeMode;

//    this.client = client;
//    src =source;
//    dest =destination;
//    cls = class_;
        initComponents();
        this.setSize(500, 500);
        setLocationRelativeTo(null);
>>>>>>> 351c590fe6c0c3a681a92e4d5978f7f6de704865
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //Insilize combo box with integer:

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showAvalbtn = new javax.swing.JButton();
        bookbtn = new javax.swing.JButton();
        seatcb = new javax.swing.JComboBox<>();
        Daycb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("2)Choose a seat:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("1)Choose a day:");

        showAvalbtn.setText("Show available seat");
        showAvalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAvalbtnActionPerformed(evt);
            }
        });

        bookbtn.setText("Book");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });

        seatcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatcbActionPerformed(evt);
            }
        });

        Daycb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));
        Daycb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaycbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Trip seat booking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addComponent(seatcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(Daycb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addComponent(showAvalbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(bookbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel3)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Daycb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAvalbtn))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seatcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(bookbtn)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showAvalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAvalbtnActionPerformed
        System.out.println("in  btnShowActionPerformed");
        loadAvailability();

    }//GEN-LAST:event_showAvalbtnActionPerformed
    private void loadAvailability() {
<<<<<<< HEAD
    try {
        int dayy = Daycb.getSelectedIndex();
        System.out.print("day:");
        System.out.println(dayy);
        client.sendLine(Integer.toString(dayy));
        
        ArrayList<Integer> seats = client.requestAvailability();
        System.out.println("in  loadAvailability");


        javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
        System.out.println("passed ");

        // To fill seat combo:
        for (int s : seats) {
            if (s > 0) {
                model.addElement("Seat Number " + s);
=======
        try {
            if( changeMode==false)
            {
            int dayy = Daycb.getSelectedIndex();
            System.out.print("day:");
            System.out.println(dayy);
            client.sendLine(Integer.toString(dayy));
>>>>>>> 351c590fe6c0c3a681a92e4d5978f7f6de704865
            }

            ArrayList<Integer> seats = client.requestAvailability();
            System.out.println("in  loadAvailability");

            // هذا هو السطر اللي كنتِ تسألين عنه
            javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
            System.out.println("passed ");

            // أضفنا النصوص اللي تمثل المقاعد
            for (int s : seats) {
                if (s > 0) {
                    model.addElement("Seat Number " + s);
                }

            }

            seatcb.setModel(model);

            boolean hasAny = model.getSize() > 0;
            bookbtn.setEnabled(hasAny);

            if (!hasAny) {
                javax.swing.JOptionPane.showMessageDialog(this, "No available trips for this class/route.");
            }

        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading availability: " + ex.getMessage());
        }
<<<<<<< HEAD
        seatcb.setModel(model);

        boolean hasAny = model.getSize() > 0;
        bookbtn.setEnabled(hasAny);

        if (!hasAny) {
            javax.swing.JOptionPane.showMessageDialog(this, "No available trips for this class/route.");
        }

        } catch (IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading availability: " + ex.getMessage());
        }
}
=======
    }
>>>>>>> 351c590fe6c0c3a681a92e4d5978f7f6de704865
    private void DaycbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaycbActionPerformed

    }//GEN-LAST:event_DaycbActionPerformed

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed

        System.out.println("In bookbtnActionPerformed");
<<<<<<< HEAD
        
        String n =String.valueOf(seatcb.getSelectedItem());
        System.out.print("Seat number:");
        System.out.println(n);
        client.sendLine(n);
        
        client.sendLine("Book");
        
        try{
        String check=client.readLine();
        JOptionPane.showMessageDialog(this, "Booking confirmed successfully!");
         if(check.equals("done"))
            dispose();
         client.disconnec();
        }
        catch (IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Booking error: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_bookbtnActionPerformed

=======

        //int d;
        //client.sendLine(dayy);
        //System.out.println("Yes am selected " + d);
        //client.sendLine(dayy); 
        String n = String.valueOf(seatcb.getSelectedItem());
        System.out.print("Seat number:");
        System.out.println(n);
        client.sendLine(n);

        try {
            String booked = client.readLine();
            System.out.println(booked);
            if (booked.equals("true")) {
                client.sendLine("CHANGE");
                new Availability(client, true).setVisible(true);
                dispose();
                return;
            } else {
       
                client.sendLine("CONFIRM");

                String check = client.readLine();
                if (check.equals("done")) {
                    dispose();
                }
            }
            client.disconnec();
        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Booking error: " + ex.getMessage());
        }

//        int snum = 0;
//        switch(n){
//            case "Seat Number 1":
//                snum=0;
//                break;
//            case "Seat Number 2":
//                snum=1;
//                break;
//            case "Seat Number 3":
//                snum=2;
//                break;
//            case "Seat Number 4":
//                snum=3;
//                break;
//            default:
//                snum=0;
//                        }
//        if(snum ==0)
//            javax.swing.JOptionPane.showMessageDialog(this, "Please select a day/trip first.");
//        return;
//          try {
//        // نستخدم دالتك الحالية reserve(...) لأنها ترسل: Source, Dest, Class, ثم تقرأ AVAIL, ثم ترسل day
//        // قيمة "seat" ما تُستخدم بالسيرفر الآن، فأرسلي أي قيمة مثل "1"
//        String result = client.reserve(src, dest, cls, n, String.valueOf(dayy));
//        javax.swing.JOptionPane.showMessageDialog(this, result);
//        if (result.toLowerCase().contains("confirmed")) {
//            dispose(); // سكري الفريم بعد نجاح الحجز
//        }}
//    }
//        client.sendLine(n);
        //client.sendLine("BOOK");

    }//GEN-LAST:event_bookbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed

    }//GEN-LAST:event_backbtnActionPerformed

>>>>>>> 351c590fe6c0c3a681a92e4d5978f7f6de704865
    private void seatcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatcbActionPerformed

    }//GEN-LAST:event_seatcbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Availability().setVisible(true));
    }
<<<<<<< HEAD
=======

   

    private void showaAvailability() {

        try {
            ArrayList<Integer> seats = client.requestAvailability();
            System.out.println("in  loadAvailability");

            // هذا هو السطر اللي كنتِ تسألين عنه
            javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
            System.out.println("passed ");

            // أضفنا النصوص اللي تمثل المقاعد
            for (int s : seats) {
                if (s > 0) {
                    model.addElement("Seat Number " + s);
                }
            }

            seatcb.setModel(model);

            boolean hasAny = model.getSize() > 0;
            bookbtn.setEnabled(hasAny);

            if (!hasAny) {
                javax.swing.JOptionPane.showMessageDialog(this, "No available trips for this class/route.");
            }

        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading availability: " + ex.getMessage());
        }
    }
>>>>>>> 351c590fe6c0c3a681a92e4d5978f7f6de704865


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Daycb;
    private javax.swing.JButton bookbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> seatcb;
    private javax.swing.JButton showAvalbtn;
    // End of variables declaration//GEN-END:variables

}
