/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClientSide;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import ClientSide.Client;


/**
 *
 * @author sarah
 */
public class Availability extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Availability.class.getName());

    /**
     * Creates new form Availability101
     */
    public Availability() {
        initComponents();
    }
    //Declaration of the var:
    String src, dest, cls;
    Client  client ;
    public Availability(Client client, String source, String destination, String class_) {
    this.client = client;
    src =source;
    dest =destination;
    cls = class_;
    initComponents(); 
    this.setSize(500, 500); 
    setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //Insilize combo box with integer:
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showAvalbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        bookbtn = new javax.swing.JButton();
        seatcb = new javax.swing.JComboBox<>();
        Daycb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("2)Choose a seat:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("1)Choose a day:");

        showAvalbtn.setText("Show available seat");
        showAvalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAvalbtnActionPerformed(evt);
            }
        });

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        bookbtn.setText("Book");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });

        seatcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatcbActionPerformed(evt);
            }
        });

        Daycb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Sautrday" }));
        Daycb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaycbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Trip seat booking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(backbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(Daycb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showAvalbtn)
                                    .addComponent(bookbtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(seatcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Daycb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAvalbtn))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seatcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookbtn)
                    .addComponent(backbtn))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void showAvalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAvalbtnActionPerformed
        System.out.println("in  btnShowActionPerformed");
        loadAvailability();
    }//GEN-LAST:event_showAvalbtnActionPerformed
    private void loadAvailability() {
    try {
        ArrayList<Integer> seats = client.requestAvailability();
                       System.out.println("in  loadAvailability");


        // هذا هو السطر اللي كنتِ تسألين عنه
        javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
        System.out.println("passed ");

        // أضفنا النصوص اللي تمثل المقاعد
        for (int s : seats) {
            if (s > 0) {
                model.addElement("Seat Number " + s);
            }
        }

        seatcb.setModel(model);

        boolean hasAny = model.getSize() > 0;
        bookbtn.setEnabled(hasAny);

        if (!hasAny) {
            javax.swing.JOptionPane.showMessageDialog(this, "No available trips for this class/route.");
        }

    } catch (IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading availability: " + ex.getMessage());
    }
}
    private void DaycbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaycbActionPerformed
       
    }//GEN-LAST:event_DaycbActionPerformed

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
    client.sendLine("BOOK");
    
    }//GEN-LAST:event_bookbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        
    }//GEN-LAST:event_backbtnActionPerformed

    private void seatcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatcbActionPerformed
        String n =(String)seatcb.getSelectedItem();
        int snum = 0;
        switch(n){
            case "Seat Number 1":
                snum=1;
                break;
            case "Seat Number 2":
                snum=2;
                break;
            case "Seat Number 3":
                snum=3;
                break;
            case "Seat Number 4":
                snum=4;
                break;
            default:
                snum=0;
                        }
        if(snum ==0)
            //Massage
            
        client.sendLine(Integer.toString(snum));
    }//GEN-LAST:event_seatcbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Availability().setVisible(true));
    }
    private void showaAvailability(){
        int d;
        switch((String) Daycb.getSelectedItem()){
            case"Sunday":
                d=1;
                break;
            case "Monday":
                d=2;
                break;
            case "Tuesday":
                d=3;
                break;
            case "Wednesday":
                d=4;
                break;
            case "Thursday":
                d=5;
                break;
            case "Friday":
                d=6;
                break;
            case "Saturday":
                d=7;
                break;
            default:
                d = 0;
        }
        client.sendLine(Integer.toString(d));
        try{
            ArrayList<Integer> seats = client.requestAvailability();
                       System.out.println("in  loadAvailability");


        // هذا هو السطر اللي كنتِ تسألين عنه
        javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
        System.out.println("passed ");

        // أضفنا النصوص اللي تمثل المقاعد
        for (int s : seats) {
            if (s > 0) {
                model.addElement("Seat Number " + s);
            }
        }

        seatcb.setModel(model);

        boolean hasAny = model.getSize() > 0;
        bookbtn.setEnabled(hasAny);

        if (!hasAny) {
            javax.swing.JOptionPane.showMessageDialog(this, "No available trips for this class/route.");
        }

    } catch (IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading availability: " + ex.getMessage());
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Daycb;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton bookbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> seatcb;
    private javax.swing.JButton showAvalbtn;
    // End of variables declaration//GEN-END:variables

}
